CREATE DATABASE PROJECT

USE PROJECT

CREATE TABLE SIGNUP
(
	FNAME VARCHAR(25) NOT NULL,
	LNAME VARCHAR(20) ,
	EMAIL VARCHAR(150) UNIQUE,
    OCCUPATION VARCHAR(159),
    CONTACT VARCHAR(15) UNIQUE,
    QUESTION VARCHAR(150),
    ANSWER VARCHAR(200),
	SPASSWORD VARCHAR(150),
    CPASSWORD VARCHAR(150)
)
INSERT INTO SIGNUP VALUES("SANGAM","GUPTA","SANGAMKG11@GMAIL.COM","STUDENT","+917905119870","NAME","SANGM","skg790","skg790")

DROP TABLE CREDIT
USE PROJECT

--create a new table for credit
CREATE TABLE CREDIT
(
DATE VARCHAR(50) NOT NULL,
AMOUNT_CREDIT INT NOT NULL,
MODE_OF_CREDIT VARCHAR(100) NOT  NULL
)
INSERT INTO CREDIT VALUES("DATE",AMOUNT_CREDIT,"MODE OF CREDIT")


-- CREATE THE NEW TABLE FOR THE DEBIT OPTION
CREATE TABLE DEBIT
(
DATE VARCHAR(50) NOT NULL,
MONEY_SPEND_ON VARCHAR(100) NOT NULL,
AMOUNT_DEBIT INT NOT NULL,
MODE_OF_DEBIT VARCHAR(100) NOT NULL
)
INSERT INTO DEBIT VALUES("DATE","MONEY SPEND ON", AMOUNT_DEBIT,"MODE OF DEBIT")

